import { Geist, Geist_Mono, Baloo_2 } from "next/font/google";
// import { Baloo_2 } from "@next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";

const baloo2 = Baloo_2({
  // weight: "400", // or your desired weight
  subsets: ["latin"], // or other subsets
  display: "swap", // optional: improves performance and fallback
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${baloo2.className} antialiased`}>
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
